import os
import sys
import time

import pytest

from autoharness.lib import layer, skill_store


def test_write_read_roundtrip(tmp_path):
    skill_store.write_body("project", "foo", "# Foo\nbody", tmp_path)
    assert skill_store.read_body("project", "foo", tmp_path) == "# Foo\nbody"
    assert skill_store.exists("project", "foo", tmp_path)


def test_read_missing_is_none(tmp_path):
    assert skill_store.read_body("project", "x", tmp_path) is None
    assert not skill_store.exists("project", "x", tmp_path)


def test_find_two_layer_and_ambiguity(tmp_path):
    g, p = tmp_path / "g", tmp_path / "p"
    roots = {"global": g, "project": p}
    skill_store.write_body("project", "foo", "b", p)
    assert skill_store.find("foo", roots) == "project"
    assert skill_store.find("missing", roots) is None
    skill_store.write_body("global", "foo", "b", g)
    with pytest.raises(ValueError):  # same name across both layers → error to disambiguate
        skill_store.find("foo", roots)


def test_apply_delta_unique_only():
    assert skill_store.apply_delta("a X b", "X", "Y") == "a Y b"
    with pytest.raises(ValueError):
        skill_store.apply_delta("ab", "Z", "Y")          # old_string not found
    with pytest.raises(ValueError):
        skill_store.apply_delta("X and X", "X", "Y")      # old_string ambiguous (multiple matches)


def test_remove(tmp_path):
    skill_store.write_body("project", "foo", "b", tmp_path)
    skill_store.remove("project", "foo", tmp_path)
    assert not skill_store.exists("project", "foo", tmp_path)


def test_archive_restore_roundtrip_preserves_sidecar(tmp_path):
    from autoharness.lib import sidecar
    skill_store.write_body("project", "foo", "real", tmp_path)
    sidecar.create("project", "foo", anchor=3, root=tmp_path)
    skill_store.archive("project", "foo", tmp_path)
    assert not skill_store.exists("project", "foo", tmp_path)         # out of live tree
    assert (layer.archive_dir("project", tmp_path) / "foo").exists()  # parked in archive
    skill_store.restore("project", "foo", tmp_path)
    assert skill_store.read_body("project", "foo", tmp_path) == "real"    # reversible
    assert sidecar.read("project", "foo", tmp_path)["anchor"] == 3        # sidecar rode along
    assert not (layer.archive_dir("project", tmp_path) / "foo").exists()  # archive slot cleared


def test_sweep_orphans_removes_tmp_keeps_live(tmp_path):
    sdir = layer.symbol_dir("project", "foo", tmp_path)
    sdir.mkdir(parents=True)
    dead = sdir / "SKILL.md.dead.tmp"
    dead.write_text("half-written")
    old = time.time() - skill_store.ORPHAN_TMP_MIN_AGE_S - 1
    os.utime(dead, (old, old))
    skill_store.write_body("project", "foo", "real", tmp_path)
    (sdir / ".sidecar.json").write_text('{"created_by": "agent"}')  # ours: the sweep only cleans its own
    removed = skill_store.sweep_orphans("project", tmp_path)
    assert removed and all(str(r).endswith(".tmp") for r in removed)
    assert skill_store.read_body("project", "foo", tmp_path) == "real"  # live file intact
    assert list(layer.skills_dir("project", tmp_path).rglob("*.tmp")) == []


def test_sweep_orphans_leaves_a_tmp_that_may_still_be_in_flight(tmp_path):
    # another hook's atomic write sits as a fresh .tmp until its rename; deleting it loses that write
    sdir = layer.symbol_dir("project", "foo", tmp_path)
    sdir.mkdir(parents=True)
    fresh = sdir / ".sidecar.json.abc12345.tmp"
    fresh.write_text("{}")
    assert skill_store.sweep_orphans("project", tmp_path) == []
    assert fresh.exists()


def _aged(p):
    old = time.time() - skill_store.ORPHAN_TMP_MIN_AGE_S - 1
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("x")
    os.utime(p, (old, old))
    return p


def test_sweep_orphans_touches_only_skills_autoharness_wrote(tmp_path):
    # README: everything not generated by autoharness is left completely alone, .tmp files included
    skills = layer.skills_dir("project", tmp_path)
    archive = layer.archive_dir("project", tmp_path)
    ours = skills / "ours"
    (ours / ".sidecar.json").parent.mkdir(parents=True)
    (ours / ".sidecar.json").write_text('{"created_by": "agent"}')
    old_ours = archive / "old-ours"
    (old_ours).mkdir(parents=True)
    (old_ours / ".sidecar.json").write_text('{"created_by": "agent"}')
    gone = [_aged(ours / "scripts" / "run.sh.ab12cd34.tmp"), _aged(old_ours / "SKILL.md.ef56gh78.tmp"),
            _aged(skills / "died-in-sidecar-write" / ".sidecar.json.zz99yy88.tmp")]
    kept = [_aged(skills / "users-skill" / "templates" / "config.tmp"), _aged(archive / "users-old" / "notes.tmp")]
    (skills / "users-skill" / "SKILL.md").write_text("mine")
    (archive / "users-old" / "SKILL.md").write_text("mine")
    removed = skill_store.sweep_orphans("project", tmp_path)
    assert sorted(removed) == sorted(gone)
    assert all(p.exists() for p in kept) and not any(p.exists() for p in gone)


def test_sweep_orphans_does_not_follow_a_linked_skill_dir(tmp_path, dir_link):
    outside = tmp_path / "outside"
    outside.mkdir()
    (outside / ".sidecar.json").write_text('{"created_by": "agent"}')
    victim = _aged(outside / "data.tmp")
    skills = layer.skills_dir("project", tmp_path)
    skills.mkdir(parents=True)
    dir_link(skills / "linked", outside)
    assert skill_store.sweep_orphans("project", tmp_path) == []
    assert victim.exists()


def test_sweep_orphans_does_not_walk_a_linked_archive(tmp_path, dir_link):
    outside = tmp_path / "outside"
    (outside / "old-ours").mkdir(parents=True)
    (outside / "old-ours" / ".sidecar.json").write_text('{"created_by": "agent"}')
    victim = _aged(outside / "old-ours" / "valuable.tmp")
    skills = layer.skills_dir("project", tmp_path)
    skills.mkdir(parents=True)
    dir_link(skills / ".archive", outside)
    assert skill_store.sweep_orphans("project", tmp_path) == []
    assert victim.exists()


def test_sweep_orphans_skips_odd_metadata_instead_of_failing(tmp_path):
    # a sweep error would abort the whole drain before any intent is read
    skills = layer.skills_dir("project", tmp_path)
    for i, meta in enumerate(["[]", "null", "42", "{not json"]):
        d = skills / f"odd{i}"
        d.mkdir(parents=True)
        (d / ".sidecar.json").write_text(meta)
        _aged(d / "x.tmp")
    assert skill_store.sweep_orphans("project", tmp_path) == []


@pytest.mark.skipif(sys.platform == "win32" or os.geteuid() == 0, reason="POSIX permissions, non-root")
def test_sweep_orphans_survives_an_unreadable_archive(tmp_path):
    skills = layer.skills_dir("project", tmp_path)
    ours = skills / "ours"
    ours.mkdir(parents=True)
    (ours / ".sidecar.json").write_text('{"created_by": "agent"}')
    gone = _aged(ours / "x.tmp")
    archive = layer.archive_dir("project", tmp_path)
    archive.mkdir()
    archive.chmod(0)
    try:
        assert skill_store.sweep_orphans("project", tmp_path) == [gone]
    finally:
        archive.chmod(0o755)


@pytest.mark.skipif(sys.platform == "win32" or os.geteuid() == 0, reason="POSIX permissions, non-root")
def test_sweep_orphans_survives_an_unreadable_skills_dir(tmp_path):
    # one locked-down layer must not stop the drain for the other
    skills = layer.skills_dir("global", tmp_path)
    skills.mkdir(parents=True)
    skills.chmod(0)
    try:
        assert skill_store.sweep_orphans("global", tmp_path) == []
    finally:
        skills.chmod(0o755)
